# -*- coding: utf-8 -*-
"""Final_Insyaallah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCWGiSkZruigqD0rvYQl23LzsDIoDqSn
"""

import re
import unicodedata
import difflib
from typing import List
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from unidecode import unidecode


"""1) Emoji → huruf/angka + hapus Variation Selector 16"""

VS16 = "\uFE0F"
COEN = "\u20E3"

def remove_variation_selectors(s: str) -> str:
    s = s.replace(COEN, "")
    s = s.replace(VS16, "")
    return s

def _emoji_digit_word_to_int(name: str):
    """Helper 'KEYCAP DIGIT NINE' / 'CIRCLED DIGIT ONE'."""
    words_to_num = {
        "ZERO": 0, "ONE": 1, "TWO": 2, "THREE": 3, "FOUR": 4,
        "FIVE": 5, "SIX": 6, "SEVEN": 7, "EIGHT": 8, "NINE": 9
    }
    parts = name.split()
    for i in range(len(parts)-1):
        if parts[i] == "DIGIT":
            return words_to_num.get(parts[i+1])
    return None

def emoji_letter_digit_to_ascii(s: str) -> str:
    out = []
    for ch in s:
        try:
            name = unicodedata.name(ch)
        except ValueError:
            out.append(ch)
            continue

        # dagger lookalikes → 't'
        if "DAGGER" in name:
            out.append("t")
            continue

        # regional indicators 🇦..🇿 → huruf ASCII
        if "REGIONAL INDICATOR SYMBOL LETTER" in name:
            out.append(name.split()[-1])
            continue

        # SQUARED/CIRCLED/NEGATIVE CIRCLED/BUTTON letters → huruf ASCII
        if "LATIN CAPITAL LETTER" in name and (
            "SQUARED" in name or "CIRCLED" in name or "NEGATIVE CIRCLED" in name or name.endswith("BUTTON")
        ):
            out.append(name.split()[-1])
            continue

        # keycap/enclosed numbers → digit 0–9
        if "KEYCAP" in name and "DIGIT" in name:
            n = _emoji_digit_word_to_int(name)
            out.append(str(n) if n is not None else ch)
            continue

        # angka enclosed/circled
        try:
            val = unicodedata.numeric(ch)
            if float(val).is_integer() and 0 <= int(val) <= 9:
                out.append(str(int(val)))
                continue
        except Exception:
            pass

        out.append(ch)
    return "".join(out)

def normalize_emoji_text(s: str) -> str:
    s = remove_variation_selectors(s)
    s = emoji_letter_digit_to_ascii(s)
    return s


"""2) Unicode normalize (NFKC) + normalisasi punct/bracket/case"""

_DASHES = re.compile(r"[\u2010\u2011\u2012\u2013\u2014\u2015\u2212]")
_APOS   = re.compile(r"[\u2018\u2019\u02BC]")
_ZW     = re.compile(r"[\u200B-\u200F\uFEFF]")
_BRACKET_BUKA  = re.compile(r'[\[\{\(【［〔｢]')
_BRACKET_TUTUP = re.compile(r'[\]\}\)】］〕｣]')

def normalize_unicode(text: str) -> str:
    return unicodedata.normalize("NFKC", text)

def normalize_punct(text: str) -> str:
    text = _DASHES.sub("-", text)
    text = _APOS.sub("'", text)
    text = _ZW.sub("", text)
    return text

def normalize_bracket(text: str) -> str:
    text = _BRACKET_BUKA.sub("[", text)
    text = _BRACKET_TUTUP.sub("]", text)
    return text

def to_lower(text: str) -> str:
    return text.lower()


"""3) Remove URL/mention/hashtag + bracket steril"""

_RE_URLS     = re.compile(r'https?://\S+|www\.\S+', re.I)
_RE_MENTIONS = re.compile(r'(?<![A-Za-z0-9_])@[a-zA-Z0-9_-]+')
_RE_HASHTAGS = re.compile(r'(?<!\w)#\w+')
_RE_BRACKETS = re.compile(r'[\[\]]')

def remove_urls_mentions_hashtags(text: str) -> str:
    text = _RE_URLS.sub(" ", text)
    text = _RE_MENTIONS.sub(" ", text)
    # text = _RE_HASHTAGS.sub(" ", text)
    return text

def remove_bracket(text: str) -> str:
    return _RE_BRACKETS.sub("", text)

"""4) Hapus timestamps jam:menit:detik"""

_TS = re.compile(r"""\b(?:[01]?\d|2[0-3])\s*[:：;]\s*[0-5]\d(?:\s*[:：;]\s*[0-5]\d)?\b""", re.X)
def remove_timestamps(s: str) -> str:
    return _TS.sub(" ", s)

"""5) Akrítik + homoglyph folding"""

def strip_combining_marks(text: str) -> str:
    d = unicodedata.normalize("NFKD", text)
    f = "".join(ch for ch in d if unicodedata.category(ch) != "Mn")
    return unicodedata.normalize("NFKC", f)

HOMO_MAP = {
    # Cyrillic
    "А": "A", "а": "a", "В": "B", "в": "b", "Е": "E", "е": "e", "К": "K", "к": "k", "М": "M", "Т": "T",
    "Х": "X", "х": "x", "О": "O", "о": "o", "Н": "H", "н": "h", "Р": "P", "р": "p", "С": "C", "с": "c",
    "У": "Y", "у": "y", "З": "Z", "з": "z", "Я": "R", "Ч": "4", "Ж": "X", "Ц": "LL", "і": "i", "ј": "j",
    "ѕ": "s", "ѡ": "w", "ә": "e", "б": "6", "г": "r", "д": "a", "и": "u", "й": "u", "л": "n", "м": "m",
    "п": "n", "т": "t", "ф": "o", "ц": "u", "ш": "w", "щ": "w", "ъ": "b", "ы": "bi", "ь": "b", "э": "e",
    "ю": "io", "я": "r", "ї": "i", "є": "e",

    # ARMENIAN LETTERS
    'Ա': 'U', 'ա': 'w', 'Բ': 'B', 'բ': 'b', 'Գ': '9', 'գ': 'q', 'Դ': 'N', 'դ': 'n', 'Ե': 'E', 'ե': 't',
    'Զ': 'Z', 'զ': 'q', 'Է': 'E', 'է': 't', 'Ը': 'P', 'ը': 'p', 'Թ': 'P', 'թ': 'p', 'Ժ': 'D', 'ժ': 'd',
    'Ի': 'H', 'ի': 'h', 'Լ': 'L', 'լ': 'l', 'Խ': 'X', 'խ': 'x', 'Ծ': 'G', 'ծ': 'd', 'Կ': 'Y', 'կ': 'k',
    'Հ': 'H', 'հ': 'h', 'Ձ': 'A', 'ձ': 'a', 'Ղ': 'N', 'ղ': 'n', 'Ճ': 'U', 'ճ': 'u', 'Մ': 'M', 'մ': 'u',
    'Յ': 'J', 'յ': 'j', 'Ն': 'U', 'ն': 'u', 'Շ': '2', 'շ': '2', 'Ո': 'N', 'ո': 'n', 'Չ': '4', 'չ': 'n',
    'Պ': 'M', 'պ': 'm', 'Ջ': '2', 'ջ': '2', 'Ռ': 'N', 'ռ': 'n', 'Ս': 'U', 'ս': 'u', 'Վ': '4', 'վ': '4',
    'Տ': 'T', 'տ': 't', 'Ր': 'R', 'ր': 'r', 'Ց': 'G', 'ց': 'g', 'Ւ': 'L', 'ւ': 'L', 'Փ': 'P', 'փ': 'p',
    'Ք': 'P', 'ք': 'p', 'Օ': 'O', 'օ': 'o', 'Ֆ': 'F', 'ֆ': 'f',

    # GREEK
    "η": "n", "Η": "H", "σ": "o", "ς": "o", "Σ": "S", "ο": "o", "Ο": "O", "ρ": "p", "Ρ": "P", "κ": "k",
    "Κ": "K", "ν": "v", "Ν": "N", "τ": "t", "Τ": "T", "χ": "x", "Χ": "X", "μ": "m", "Μ": "M", "λ": "a",
    "Λ": "a", "α": "a", "β": "b", "γ": "y", "δ": "d", "ε": "e", "ζ": "z", "θ": "0", "ι": "i", "ξ": "e",
    "π": "n", "υ": "u", "φ": "o", "ψ": "w", "ω": "w", "ϲ": "c", "ϵ": "e", "Ϛ": "s", "ϫ": "x", "Α": "A",
    "Β": "B", "Δ": "A", "Γ": "r", "Ω": "W", "Ϝ": "F",

    # CJK UNIFIED & KANJI
    "丅": "t", "丄": "t", "丫": "y", "厶": "a", "乇": "e", "乚": "l", "囗": "o", "工": "i", "尺": "r", "丁": "t",
    "十": "t", "一": "-", "二": "=", "三": "e", "口": "o", "人": "y", "入": "y", "X": "x", "匕": "t", "マ": "v",
    "ム": "a", "カ": "n", "丨": "I", "亅": "J", "ロ": "O", "回": "O", "曰": "O", "乂": "X", "⻌": "Z", "八": "a",
    "〇": "0",

    # SMALL CAPITALS
    'ᴀ': 'a', 'ʙ': 'b', 'ᴄ': 'c', 'ᴅ': 'd', 'ᴇ': 'e', 'ғ': 'f', 'ɢ': 'g', 'ʜ': 'h', 'ɪ': 'i', 'ᴊ': 'j', 'ᴋ': 'k',
    'ʟ': 'l', 'ᴍ': 'm', 'ɴ': 'n', 'ᴏ': 'o', 'ᴘ': 'p', 'ꞯ': 'q', 'ʀ': 'r', 'ꜱ': 's', 'ᴛ': 't', 'ᴜ': 'u', 'ᴠ': 'v',
    'ᴡ': 'w', 'x': 'x', 'ʏ': 'y', 'ᴢ': 'z',

    # varian visual angka/huruf
    '𝟶': '0', '𝟷': '1', '𝟸': '2', '𝟹': '3', '𝟺': '4', '𝟻': '5', '𝟼': '6', '𝟽': '7', '𝟾': '8', '𝟿': '9',
    '𝟢': '0', '𝟣': '1', '𝟤': '2', '𝟹': '3', '𝟺': '4', '𝟻': '5', '𝟼': '6', '𝟽': '7', '𝟾': '8', '𝟿': '9',

    # CANADIAN SYLLABICS
    'ᗩ': 'a', 'ᐯ': 'v', 'ᐠ': 'v', 'ᑕ': 'c', 'ᑐ': 'j', 'ᗷ': 'b', 'ᑌ': 'u', 'ᑎ': 'n', 'ᑘ': 'u', 'ᑭ': 'p', 'ᑯ': 'd',
    'ᑲ': 'b', 'ᑫ': 'q', 'ᕒ': 'p', 'ᙀ': 'q', 'ᒪ': 'l',  'ᒧ': 'j', 'ᒥ': 'r', 'ᗰ': 'm', 'ᗯ': 'w', 'ᙡ': 'w', 'ᔕ': 's',
    'ᔅ': 'z', '᙭': 'x', 'ᔦ': 'y', 'ᕼ': 'h', 'ᖇ':'r',

    # --- MATHEMATICAL SCRIPT (HURUF KURSIF) ---
    '𝒜': 'A', '𝒞': 'C', '𝒟': 'D', '𝒢': 'G', '𝒥': 'J', '𝒦': 'K', '𝒩': 'N', '𝒪': 'O', '𝒫': 'P', '𝒬': 'Q',
    '𝒮': 'S', '𝒯': 'T', '𝒰': 'U', '𝒱': 'V', '𝒲': 'W','𝒳': 'X', '𝒴': 'Y', '𝒵': 'Z',
    'ℬ': 'B', 'ℰ': 'E', 'ℱ': 'F', 'ℋ': 'H', 'ℐ': 'I', 'ℒ': 'L', 'ℳ': 'M', 'ℛ': 'R', '𝒶': 'a',
    '𝒷': 'b', '𝒸': 'c', '𝒹': 'd', '𝒻': 'f', '𝒽': 'h', '𝒾': 'i', '𝒿': 'j', '𝓀': 'k', '𝓁': 'l', '𝓂': 'm', '𝓃': 'n', '𝓅': 'p', '𝓆': 'q',
    '𝓇': 'r', '𝓈': 's', '𝓉': 't', '𝓊': 'u', '𝓋': 'v', '𝓌': 'w', '𝓍': 'x', '𝓎': 'y', '𝓏': 'z', 'ℯ': 'e', 'ℊ': 'g', 'ℴ': 'o',

    # --- LATIN EXTENDED (HOOKS, BARS, STROKES) ---
    'Ɦ': 'H', 'ƙ': 'k', 'ƣ': 'g', 'ʞ': 'k', 'Ħ': 'H', 'ħ': 'h', 'Ɨ': 'I', 'ɨ': 'i', 'ł': 'l', 'Ɵ': 'O', 'Ɱ': 'M',
    'Ⱡ': 'L', 'Ⱨ': 'H', 'Ɽ': 'R', 'Ꜹ': 'A',

    # Emoji
    # '🏵':'o'
}

def fold_homoglyphs(text: str) -> str:
    return "".join(HOMO_MAP.get(ch, ch) for ch in text)


"""# lexicon_alay"""

# def fold_alay(text: list) -> list:
#   text = text.split()
#   out = [lexicon_alay[x] for x in text if x in lexicon_alay]
#   return out

"""# lexicon end"""

def transliterasi_teks(teks_unicode):
  return unidecode(teks_unicode)


"""6) Intraword symbols handling"""

_PUNCT_MIDWORD = r"[',.!?\u2026;]+"

def _allowed_chars(keep_at: bool) -> str:
    return r"@._\-" if keep_at else r"._\-"

def handle_intraword_symbols(text: str, *, keep_at: bool = True) -> str:
    allowed = _allowed_chars(keep_at)

    # punctuation di tengah kata/angka → spasi
    text = re.sub(rf"(?iu)(?<=\w){_PUNCT_MIDWORD}(?=\w)", " ", text)

    # karakter aneh yang bukan huruf/angka/allowed diapit non boundary → spasi
    text = re.sub(rf"(?iu)[^\w{allowed}\s]+", " ", text)

    return re.sub(r"\s+", " ", text).strip()

"""7) Whitelist global + squeeze spaces"""

def keep_alnum_and_space(text: str) -> str:
    return re.sub(r"[^0-9a-zA-Z@!\$%]+", " ", text)

def squeeze_spaces(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()

"""9) Rejoin huruf terpisah & trailing digits"""

VOWELS = set("aiueo")

def rejoin_split_letters(tokens: List[str]) -> List[str]:
    out, i, n = [], 0, len(tokens)
    while i < n:
        j, letters = i, []
        # gabungkan huruf terpisah: p u l a u → pulau
        while j < n and re.fullmatch(r'[A-Za-z]', tokens[j]):
            letters.append(tokens[j].lower())
            j += 1
        if len(letters) >= 3:
            word = ''.join(letters)
            # kalau setelah huruf terpisah ada digit, gabungkan: p u l a u 7 7 7 → pulau777
            k, digits = j, []
            while k < n and re.fullmatch(r'\d+', tokens[k]):
                digits.append(tokens[k]); k += 1
            if digits:
                word += ''.join(digits)
                j = k
            if any(ch in VOWELS for ch in word) and 3 <= len(word) <= 24:
                out.append(word)
                i = j
                continue

        # blok digit murni
        if re.fullmatch(r'\d+', tokens[i]):
            k, digits = i, []
            while k < n and re.fullmatch(r'\d+', tokens[k]):
                digits.append(tokens[k]); k += 1
            digits_str = ''.join(digits)
            out.append(digits_str)
            i = k
            continue

        # default: token lain lewat saja
        out.append(tokens[i])
        i += 1

    return out

"""10) Heuristik angka dinamis untuk konteks promosi"""


"""# 11) Leet/Plesetan Normalization"""

def koreksi_kalimat(sentence: list, target_phrases: dict) -> list:

    # 1. Pisahkan kalimat menjadi list of words (token)

    # Tentukan ukuran jendela maksimal yang akan diperiksa.
    # Ini didasarkan pada panjang karakter frasa target terpanjang.
    if not target_phrases:
        return sentence
    max_window_size = max(len(key) for key in target_phrases.keys())

    corrected_tokens = []
    i = 0
    while i < len(sentence):
        found_match = False

        # 2. Geser jendela dari ukuran terbesar ke terkecil
        # untuk memprioritaskan pencocokan frasa terpanjang terlebih dahulu.
        for window_size in range(max_window_size, 0, -1):
            # Pastikan jendela tidak melebihi batas list
            if i + window_size > len(sentence):
                continue

            # 3. Ambil jendela kata dan gabungkan
            window = sentence[i : i + window_size]
            concatenated_phrase = "".join(window)

            # 4. Normalisasi frasa yang digabung untuk pencocokan
            # (huruf kecil, hapus semua non-alphanumeric)
            normalized_phrase = re.sub(r'[^a-zA-Z0-9]', '', concatenated_phrase).lower()

            # 5. Cek apakah frasa yang dinormalisasi ada di kamus target
            if normalized_phrase in target_phrases:
                # Jika cocok, tambahkan versi yang benar ke hasil
                corrected_tokens.append(target_phrases[normalized_phrase])
                # Loncat indeks sejauh ukuran jendela
                i += window_size
                found_match = True
                break

        # 6. Jika tidak ada kecocokan, gunakan token asli
        if not found_match:
            corrected_tokens.append(sentence[i])
            i += 1

    # 7. Gabungkan kembali token yang sudah dikoreksi menjadi kalimat
    return corrected_tokens


daftar_target = {
    'garudahoki': 'garudahoki',
    'digarudahoki': 'digarudahoki',
    'pulau777': 'pulau777',
    'garuda': 'garuda',
    'digaruda': 'garuda',
    'mona4d':'mona4d',
    'dimona4d':'dimona4d',
    'alexis17':'alexis17',
    'pulau':'pulau',
    'dipulau':'dipulau',
    '25kbet':'25kbet',
    'alexis17':'alexis17',
    'arwanatoto':'arwanatoto',
    'istanabet17':'istanabet17',
    'weton88':'weton88',
    'gelora4d':'gelora4d',
    'probet 855':'probet 855',
    'banteng hoki':'banteng hoki',
    'hoki':'hoki',
    'sgi88':'sgi88',
    'hokii':'hoki',

}

LEET_MAP_TABLE = {'0': 'o', '1': 'i', '3': 'e', '4': 'a', '6': 'g', '5': 's', '@': 'a', '9':'g', '!':'i'}
_RE_AT_INFIX = re.compile(r'(?i)(?<=[a-z])@(?=[a-z])')
_RE_ALNUM_MIX = re.compile(r'(?i)(?:[a-z]+\d+|\d+[a-z]+)')

def map_chars(tok: str) -> str:
    t = tok
    # kalau brand 4d, jangan diutak-atik di sini
    if t.lower().endswith('4d'):
        return t

    # ganti @ di tengah kata jadi 'a' (contoh m@xwin → maxwin)
    t = _RE_AT_INFIX.sub('a', t)

    out = []
    n, i = len(t), 0
    while i < n:
        ch = t[i]
        if ch.isdigit():
            j = i + 1
            while j < n and t[j].isdigit():
                j += 1
            run_len = j - i
            # run digit ≥ 2 → biarkan apa adanya
            if run_len >= 2:
                out.append(t[i:j])
            else:
                # 1 digit → boleh dipetakan jadi huruf (4 → a, 0 → o, dll)
                out.append(LEET_MAP_TABLE.get(ch, ch))
            i = j
            continue
        # huruf/simbol → map kalau ada di LEET_MAP_TABLE
        out.append(LEET_MAP_TABLE.get(ch, ch))
        i += 1
    return ''.join(out)

SUBS = {
    # MAXWIN
    'maxw!n': 'maxwin',
    'maxwinn': 'maxwin',
    'm14xwin': 'maxwin',
    'm4ksvin': 'maxwin',

    # SLOT
    '5lot': 'slot',
    's1ot': 'slot',
    'slott': 'slot',
    'sloot': 'slot',
    's|ot': 'slot',
    'sl07': 'slot',
    's!ot': 'slot',

    'sgpin': 'spin',

    # GACOR
    'gacoor':'gacor',
    'g4k0r':'gacor',
    'ggacor':'gacor',
    '9acor':'gacor',

    # HOKI
    'hokii': 'hoki',
    'hokl': 'hoki',
    'h0kl':'hoki',

    # LAIN
    'bette':'bet',
    'wdw':'wd',
    'w1d':'wd',
    't0g3ll':'togel',
    'pr0m':'promo',
    'b0nuss':'bonus',
    'garudahokl':'garudahoki',
    '9aruda':'garuda',
    'arwanatt':'arwanatoto',
    't0to':'toto'

}

DOMAIN_WORDS = {
    "maxwin","gacor","slot","spin","garudahoki","pulau","hoki",
    "deposit","depo","wd","jackpot","togel","casino","promo","bonus","bet", "4d"
}

def fix_infix_digits_with_domain(tok: str, domain=DOMAIN_WORDS, thr: float = 0.80) -> str:
    t = tok.lower()
    # hanya kalau ada digit di tengah huruf: s1ot, m4x, t0g3l, dll
    if not re.search(r'[a-z]\d+[a-z]', t):
        return tok
    letters_only = re.sub(r'[^a-z]', '', t)
    if len(letters_only) < 3:
        return tok
    best, best_ratio = None, 0.0
    for cand in domain:
        r = difflib.SequenceMatcher(None, letters_only, cand).ratio()
        if r > best_ratio:
            best, best_ratio = cand, r
    if best and best_ratio >= thr:
        if letters_only[0] == best[0] or letters_only[-2:] == best[-2:]:
            return best
    return tok

def squeeze_repeats(token: str, max_repeat: int = 2) -> str:
    out, cnt, prev = [], 0, ''
    for ch in token:
        if ch == prev:
            cnt += 1
            # huruf dibatasi, digit boleh berulang
            if ch.isdigit() or cnt <= max_repeat:
                out.append(ch)
        else:
            prev = ch
            cnt = 1
            out.append(ch)
    return ''.join(out)

def normalize_plesetan(tokens: List[str]) -> List[str]:
    out: List[str] = []
    for t in tokens:
        t0 = t.lower()

        # 1) full digit → biarkan, nanti filter_numbers_dynamic yang urus
        if t0.isdigit():
            out.append(t0)
            continue

        # 2) kalau token tepat ada di SUBS (m4xwin, g4c0r, sl0t, dll) → normalisasi langsung
        if t0 in SUBS:
            out.append(SUBS[t0])
            continue

        # if t0 in lexicon_alay:
        #     out.append(lexicon_alay[t0])
        #     continue

        # 3) kalau campuran huruf+angka, tapi bukan di SUBS → jangan diapa-apain (pulau777, wifi4d, 25kbet)
        if _RE_ALNUM_MIX.fullmatch(t0):
            out.append(t0)
            continue

        # 4) sisanya (huruf saja / plesetan simbol) → baru dinormalisasi
        t1 = map_chars(t0)
        t2 = SUBS.get(t1, t1)
        t3 = squeeze_repeats(t2, max_repeat=2)
        t4 = fix_infix_digits_with_domain(t3)
        t5 = SUBS.get(t4, t4)
        out.append(t5)
    result = koreksi_kalimat(out, daftar_target)
    return result

"""12) Stopword & Stemming (Sastrawi)"""

_factory_sw = StopWordRemoverFactory()
_stopwords_set = set(_factory_sw.get_stop_words())

def remove_stopwords(tokens: List[str]) -> List[str]:
    return [t for t in tokens if t not in _stopwords_set]

_factory_stem = StemmerFactory()
_stemmer = _factory_stem.create_stemmer()

def stem_tokens(tokens: List[str]) -> List[str]:
    return [_stemmer.stem(t) for t in tokens]

def removestopword_stemming(tokens: List[str]) -> List[str]:
    tokens = remove_stopwords(tokens)
    tokens = stem_tokens(tokens)
    return tokens

"""13) Pipeline utama"""

def preprocess(text: str, *, keep_at: bool = True, map_at_leet: bool = False) -> str:
    # A) Normalisasi bentuk
    text = normalize_emoji_text(text)
    text = normalize_unicode( text)
    text = normalize_punct(text)
    text = normalize_bracket(text)
    text = strip_combining_marks(text)
    text = fold_homoglyphs(text)


    # B) Noise pola khusus
    text = remove_urls_mentions_hashtags(text)
    text = remove_timestamps(text)
    text = remove_bracket(text)

    # C) Akrítik + homoglyph


    # D) Intraword symbols
    text = handle_intraword_symbols(text, keep_at=keep_at)


    text = transliterasi_teks(text)
    text = to_lower(text)

    # E) Whitelist + spasi
    text = keep_alnum_and_space(text)
    text = squeeze_spaces(text)



    # G) Rejoin huruf terpisah (+ trailing digits)
    tokens = text.split()
    tokens = rejoin_split_letters(tokens)

    # H) Plesetan + angka dinamis + stopword+stemming
    tokens = normalize_plesetan(tokens)
    tokens = removestopword_stemming(tokens)

    return squeeze_spaces(' '.join(tokens))